[package]
name = "chatbot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.86"
chrono = { version = "0.4.39", features = ["serde"] }
chrono-tz = { version = "0.10.1", features = ["serde"] }
colog = "1.3.0"
env_logger = "0.11.6"
genai = "0.1.21"
indexmap = "2.7.1"
log = "0.4.25"
poise = "0.6.1"
qdrant-client = "1.13.0"
rand = "0.9.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"


[dependencies.openai-api-rs]
# version = "5.2.6"
git = "https://github.com/GustavoWidman/openai-api-rs"
default-features = false
features = ["rustls"]

[dependencies.branch-context]
git = "https://github.com/GustavoWidman/branch-context"
branch = "main"
